spring.output.ansi.enabled: always
spring.application.name: answer-server

logging:
  level.root: INFO

netty.server.http:
  port: 10002
  maxContentLength: 1048576
  pipelineLogLevel: INFO
  bootstrapLogLevel: INFO

netty.server.websocket:
  port: 10001
  maxContentLength: 1048576
  path: /api
  subProtocol: null
  allowExtensions: true
  pipelineLogLevel: INFO
  bootstrapLogLevel: INFO
